---
- hosts: all
  tasks:
    - name: capture listening processes
      command: "sudo netstat -plnt"
      register: listening
    - name: Write processes listening
      local_action: copy content="{{ listening.stdout }}" dest="reports/{{ansible_hostname}}.netstat"
